name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: my_gym_vault

env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  setup_ruby:
    runs-on: ubuntu-latest
    outputs:
      ruby-version: ${{ steps.set_ruby.outputs.ruby-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        id: set_ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_gym_vault/.ruby-version
          bundler-cache: true

  scan_ruby:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_gym_vault/.ruby-version
          bundler-cache: true

      - name: Scan for common Rails security vulnerabilities
        working-directory: my_gym_vault
        run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_gym_vault
          bundler-cache: true

      - name: Scan for JS dependency vulnerabilities
        working-directory: my_gym_vault
        run: bundle exec importmap audit

  lint:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_gym_vault
          bundler-cache: true

      - name: Lint code for consistent style
        working-directory: my_gym_vault
        run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest
    needs: setup_ruby

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.PG_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: my_gym_vault_test
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: my_gym_vault
          bundler-cache: true

      - name: Setup Database
        working-directory: my_gym_vault
        run: |
          bin/rails db:setup
          bin/rails db:test:prepare

      - name: Run tests
        working-directory: my_gym_vault
        env:
          DATABASE_URL: postgres://${{ secrets.PG_USERNAME }}:${{ secrets.PG_PASSWORD }}@localhost:5432/my_gym_vault_test
        run: |
          bin/rails test
          bin/rails test:system

      - name: Upload screenshots from failed system tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: my_gym_vault/tmp/screenshots
          if-no-files-found: ignore

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: my_gym_vault/log/test.log
          if-no-files-found: ignore
