name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}

jobs:
  setup_ruby:
    runs-on: ubuntu-latest
    outputs:
      ruby-version: ${{ steps.set_ruby.outputs.ruby-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        id: set_ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

  scan_ruby:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

      - name: Scan Rails app for vulnerabilities
        working-directory: my_gym_vault
        run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

      - name: Scan JS dependencies
        working-directory: my_gym_vault
        run: bundle exec importmap audit

  lint:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

      - name: Lint code
        working-directory: my_gym_vault
        run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest
    needs: setup_ruby
    env:
      PG_USERNAME: postgres
      PG_PASSWORD: postgres
      PG_DB: my_gym_vault_test
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config postgresql postgresql-client google-chrome-stable

      - name: Start PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

      - name: Setup Database
        working-directory: my_gym_vault
        run: |
          bin/rails db:create
          bin/rails db:migrate
          bin/rails db:test:prepare

      - name: Run tests
        working-directory: my_gym_vault
        run: |
          bin/rails test
          bin/rails test:system

      - name: Upload screenshots from failed system tests
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: my_gym_vault/tmp/screenshots
          if-no-files-found: ignore

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: my_gym_vault/log/test.log
          if-no-files-found: ignore
