name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: my_gym_vault

env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  PG_USERNAME: ${{ secrets.PG_USERNAME }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_DB: my_gym_vault_test

jobs:
  setup_ruby:
    runs-on: ubuntu-latest
    outputs:
      ruby-version: ${{ steps.set_ruby.outputs.ruby-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        id: set_ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

  scan_ruby:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
      - run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
      - run: bundle exec importmap audit

  lint:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
      - run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest
    needs: setup_ruby
    env:
      DATABASE_URL: postgres://${{ secrets.PG_USERNAME }}:${{ secrets.PG_PASSWORD }}@localhost:5432/my_gym_vault_test

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y build-essential git libpq-dev pkg-config postgresql-18 postgresql-client-18

      - name: Start PostgreSQL
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ secrets.PG_PASSWORD }}';"
          sudo -u postgres createdb -O postgres my_gym_vault_test || true

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

      - name: Setup Database
        run: |
          bin/rails db:setup
          bin/rails db:test:prepare

      - name: Run tests
        run: |
          bin/rails test
          bin/rails test:system

      - name: Upload screenshots from failed system tests
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: screenshots
          path: my_gym_vault/tmp/screenshots
          if-no-files-found: ignore

      - name: Upload test logs
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: test-logs
          path: my_gym_vault/log/test.log
          if-no-files-found: ignore
