name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash
    working-directory: my_gym_vault

env:
  RAILS_ENV: test
  RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
  PG_USERNAME: ${{ secrets.PG_USERNAME }}
  PG_PASSWORD: ${{ secrets.PG_PASSWORD }}
  PG_DB: my_gym_vault_test
  DATABASE_URL: postgres://${{ secrets.PG_USERNAME }}:${{ secrets.PG_PASSWORD }}@localhost:5432/my_gym_vault_test

jobs:
  setup_ruby:
    runs-on: ubuntu-latest
    outputs:
      ruby-version: ${{ steps.set_ruby.outputs.ruby-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        id: set_ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

  scan_ruby:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
      - run: bundle exec brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
      - run: bundle exec importmap audit

  lint:
    runs-on: ubuntu-latest
    needs: setup_ruby
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true
      - run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest
    needs: setup_ruby
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.PG_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.PG_PASSWORD }}
          POSTGRES_DB: my_gym_vault_test
        options: >-
          --health-cmd="pg_isready -U ${{ secrets.PG_USERNAME }}"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev libyaml-dev pkg-config google-chrome-stable
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.5
          bundler-cache: true

      - run: |
          bin/rails db:setup
          bin/rails db:test:prepare

      - run: |
          bin/rails test
          bin/rails test:system

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: my_gym_vault/tmp/screenshots
          if-no-files-found: ignore

      - if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: my_gym_vault/log/test.log
          if-no-files-found: ignore
